#include "xprec/ddouble-header-only.hpp"

#include "sparseir-fwd.hpp"

#include "./spir_status.h"
#include "./utils.hpp"
#include "./linalg.hpp"
#include "./root.hpp"
#include "./specfuncs.hpp"
#include "./freq.hpp"
#include "./svd.hpp"
#include "./gauss.hpp"
#include "./funcs.hpp"
#include "./poly.hpp"
#include "./kernel.hpp"
#include "./sve.hpp"
#include "./basis.hpp"
#include "./augment.hpp"
#include "./sampling.hpp"
#include "./dlr.hpp"
#include "./basis_set.hpp"
