#pragma once

// Status codes
#define SPIR_COMPUTATION_SUCCESS 0
#define SPIR_GET_IMPL_FAILED -1
#define SPIR_INVALID_DIMENSION -2
#define SPIR_INPUT_DIMENSION_MISMATCH -3
#define SPIR_OUTPUT_DIMENSION_MISMATCH -4
#define SPIR_NOT_SUPPORTED -5
#define SPIR_INVALID_ARGUMENT -6
#define SPIR_INTERNAL_ERROR -7
