name: Build and upload conda packages

# Triggered a new tag starting with "v" is pushed
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix .os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Set up Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        conda install conda-build anaconda-client -y

    - name: Bulid and upload
      env:
        ANACONDA_API_TOKEN: ${{secrets.ANACONDA_TOKEN}}
      run: |
        conda config --set anaconda_upload yes
        conda build .conda --user SpM-lab
